name: PowerGems
version: '${project.version}'
main: dev.iseal.powergems.PowerGems
api-version: '1.19'
author: ISeal
load: STARTUP
softdepend: [WorldGuard]
commands:
  givegem:
    description: Command to give yourself a gem
    usage: /givegem <gem>
    permission: powergems.givegem
  giveallgem:
    description: Command to give everyone a gem
    usage: /giveallgem <gem>
    permission: powergems.giveallgem
  checkupdates:
    description: Command to check for updates
    usage: /checkupdates
    permission: powergems.checkupdates
  reloadconfig:
    description: Command to reload the config files
    usage: /reloadconfig
    aliases: [rc]
    permission: powergems.reloadconfig
  debug:
    description: Debug command
    usage: /debug
    aliases: [d, db]
    permission: powergems.debug
permissions:
    powergems.givegem:
        description: Permission to use /givegem
        default: op
    powergems.giveallgem:
        description: Permission to use /giveallgem
        default: op
    powergems.checkupdates:
        description: Permission to use /checkupdates
        default: true
    powergems.reloadconfig:
        description: Permission to use /reloadconfig
        default: op
    powergems.debug:
        description: Permission to use /debug
        default: op
    powergems.*:
        description: Permission to use all PowerGems commands
        default: op
        children:
            powergems.givegem: true
            powergems.giveallgem: true
            powergems.checkupdates: true
            powergems.reloadconfig: true
            powergems.debug: true
